#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, '..');

// 颜色输出
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
};

function colorLog(color: keyof typeof colors, message: string) {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

// 生成随机字符串
function generateRandomString(length: number): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// 创建.env.local文件
function createEnvFile() {
  const envContent = `# Environment Variables
# Generated by bootstrap script on ${new Date().toISOString()}

# Application
NODE_ENV=development
NEXT_PUBLIC_APP_NAME=中餐馆点餐系统
NEXT_PUBLIC_APP_DESCRIPTION=在美国使用的中餐馆点餐系统

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:3001
API_PORT=3001
WEB_PORT=3000

# Database
DATABASE_URL="file:./data/app.db"

# Authentication
JWT_SECRET=${generateRandomString(64)}
JWT_EXPIRES_IN=1h
REFRESH_TOKEN_EXPIRES_IN=7d

# Redis (Optional)
# REDIS_URL=redis://localhost:6379

# Email (Optional)
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your-email@gmail.com
# SMTP_PASS=your-app-password
# FROM_EMAIL=noreply@yourdomain.com

# File Upload
UPLOAD_DIR=./uploads
MAX_FILE_SIZE=10485760
ALLOWED_FILE_TYPES=image/jpeg,image/png,image/gif,application/pdf

# Logging
LOG_LEVEL=info
LOG_FILE=./logs/app.log

# Development
NEXT_PUBLIC_DEV_MODE=true
`;

  fs.writeFileSync(path.join(projectRoot, '.env.local'), envContent);
  colorLog('green', '✓ 创建 .env.local 文件');
}

// 更新package.json
function updatePackageJson() {
  const packageJsonPath = path.join(projectRoot, 'package.json');
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
  
  packageJson.name = 'chinese-restaurant-system';
  packageJson.description = '在美国使用的中餐馆点餐系统';
  packageJson.author = 'jasonq';
  
  fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
  colorLog('green', '✓ 更新 package.json');
}

// 创建必要的目录
function createDirectories() {
  const directories = [
    'logs',
    'uploads',
    'data',
  ];

  directories.forEach(dir => {
    const dirPath = path.join(projectRoot, dir);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
      colorLog('green', `✓ 创建目录: ${dir}`);
    }
  });
}

// 主初始化函数
async function bootstrap() {
  colorLog('cyan', '🚀 欢迎使用 Monorepo Bootstrap 初始化工具');
  colorLog('yellow', '本工具将帮助您快速配置项目环境\n');

  try {
    colorLog('bright', '📋 项目配置');
    console.log('项目名称: 中餐馆点餐系统');
    console.log('项目描述: 在美国使用的中餐馆点餐系统');
    console.log('作者: jasonq');
    console.log('数据库类型: SQLite (开发环境推荐)');
    console.log('前端端口: 3000');
    console.log('后端端口: 3001');
    console.log('邮箱验证: 禁用');

    // 开始配置
    colorLog('\n⚙️ 开始配置项目...');

    // 更新package.json
    updatePackageJson();

    // 创建.env.local文件
    createEnvFile();

    // 创建必要目录
    createDirectories();

    colorLog('\n🎉 项目配置完成！');
    colorLog('green', '\n🚀 下一步操作:');
    console.log('  pnpm install          # 安装依赖');
    console.log('  pnpm db:generate      # 生成数据库客户端');
    console.log('  pnpm db:migrate       # 运行数据库迁移');
    console.log('  pnpm db:seed          # 初始化种子数据');
    console.log('  pnpm dev              # 启动开发服务器');

  } catch (error) {
    colorLog('red', `\n❌ 初始化失败: ${error}`);
    process.exit(1);
  }
}

// 运行初始化
bootstrap();