#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, '..');

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

// 颜色输出
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
};

function colorLog(color: keyof typeof colors, message: string) {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

// 生成随机字符串
function generateRandomString(length: number): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// 询问用户输入
function question(query: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(`${colors.cyan}${query}${colors.reset}`, (answer) => {
      resolve(answer.trim());
    });
  });
}

// 选择题
function selectQuestion(query: string, options: string[]): Promise<string> {
  return new Promise((resolve) => {
    console.log(`${colors.bright}${query}${colors.reset}`);
    options.forEach((option, index) => {
      console.log(`${colors.cyan}${index + 1}.${colors.reset} ${option}`);
    });
    
    rl.question(`${colors.yellow}请选择 (输入数字):${colors.reset} `, (answer) => {
      const index = parseInt(answer, 10) - 1;
      if (index >= 0 && index < options.length) {
        resolve(options[index]);
      } else {
        colorLog('red', '无效选择，请重新选择');
        resolve(selectQuestion(query, options));
      }
    });
  });
}

// 确认问题
function confirmQuestion(query: string): Promise<boolean> {
  return new Promise((resolve) => {
    rl.question(`${colors.yellow}${query} (y/N):${colors.reset} `, (answer) => {
      resolve(answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes');
    });
  });
}

// 更新package.json
function updatePackageJson(key: string, value: any) {
  const packageJsonPath = path.join(projectRoot, 'package.json');
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
  
  if (key.includes('.')) {
    const keys = key.split('.');
    let current = packageJson;
    for (let i = 0; i < keys.length - 1; i++) {
      if (!current[keys[i]]) current[keys[i]] = {};
      current = current[keys[i]];
    }
    current[keys[keys.length - 1]] = value;
  } else {
    packageJson[key] = value;
  }
  
  fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
}

// 创建.env.local文件
function createEnvFile(config: any) {
  const envContent = `# Environment Variables
# Generated by bootstrap script on ${new Date().toISOString()}

# Application
NODE_ENV=development
NEXT_PUBLIC_APP_NAME=${config.appName}
NEXT_PUBLIC_APP_DESCRIPTION=${config.appDescription}

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:${config.apiPort}
API_PORT=${config.apiPort}
WEB_PORT=${config.webPort}

# Database
DATABASE_URL="${config.databaseUrl}"

# Authentication
JWT_SECRET=${config.jwtSecret}
JWT_EXPIRES_IN=1h
REFRESH_TOKEN_EXPIRES_IN=7d

# Redis (Optional)
# REDIS_URL=redis://localhost:6379

# Email (Optional)
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your-email@gmail.com
# SMTP_PASS=your-app-password
# FROM_EMAIL=noreply@yourdomain.com

# File Upload
UPLOAD_DIR=./uploads
MAX_FILE_SIZE=10485760
ALLOWED_FILE_TYPES=image/jpeg,image/png,image/gif,application/pdf

# Logging
LOG_LEVEL=info
LOG_FILE=./logs/app.log

# Development
NEXT_PUBLIC_DEV_MODE=true
`;

  fs.writeFileSync(path.join(projectRoot, '.env.local'), envContent);
}

// 创建必要的目录
function createDirectories() {
  const directories = [
    'logs',
    'uploads',
    'data',
  ];

  directories.forEach(dir => {
    const dirPath = path.join(projectRoot, dir);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
      colorLog('green', `✓ 创建目录: ${dir}`);
    }
  });
}

// 主初始化函数
async function bootstrap() {
  colorLog('cyan', '🚀 欢迎使用 Monorepo Bootstrap 初始化工具');
  colorLog('yellow', '本工具将帮助您快速配置项目环境\n');

  try {
    // 项目基本信息
    colorLog('bright', '📋 项目基本信息');
    const appName = await question('项目名称: ') || 'My Awesome App';
    const appDescription = await question('项目描述: ') || '基于Monorepo Bootstrap的全栈应用';
    const author = await question('作者名称: ') || '';

    // 数据库配置
    colorLog('\n📊 数据库配置');
    const databaseType = await selectQuestion('选择数据库类型:', [
      'SQLite (开发环境推荐)',
      'PostgreSQL (生产环境推荐)',
      'MySQL',
    ]);

    let databaseUrl = '';
    switch (databaseType) {
      case 'SQLite (开发环境推荐)':
        databaseUrl = 'file:./data/app.db';
        break;
      case 'PostgreSQL (生产环境推荐)':
        const pgHost = await question('PostgreSQL主机 (localhost): ') || 'localhost';
        const pgPort = await question('PostgreSQL端口 (5432): ') || '5432';
        const pgDb = await question('数据库名称: ');
        const pgUser = await question('用户名: ');
        const pgPassword = await question('密码: ');
        databaseUrl = `postgresql://${pgUser}:${pgPassword}@${pgHost}:${pgPort}/${pgDb}`;
        break;
      case 'MySQL':
        const mysqlHost = await question('MySQL主机 (localhost): ') || 'localhost';
        const mysqlPort = await question('MySQL端口 (3306): ') || '3306';
        const mysqlDb = await question('数据库名称: ');
        const mysqlUser = await question('用户名: ');
        const mysqlPassword = await question('密码: ');
        databaseUrl = `mysql://${mysqlUser}:${mysqlPassword}@${mysqlHost}:${mysqlPort}/${mysqlDb}`;
        break;
    }

    // 端口配置
    colorLog('\n🔌 端口配置');
    const webPort = await question('前端端口 (3000): ') || '3000';
    const apiPort = await question('后端端口 (3001): ') || '3001';

    // 认证配置
    colorLog('\n🔐 认证配置');
    const jwtSecret = generateRandomString(64);
    colorLog('green', `✓ JWT密钥已生成: ${jwtSecret.substring(0, 8)}...`);

    const enableEmailVerification = await confirmQuestion('启用邮箱验证?');

    // 配置汇总
    colorLog('\n📝 配置汇总');
    console.log(`项目名称: ${appName}`);
    console.log(`项目描述: ${appDescription}`);
    if (author) console.log(`作者: ${author}`);
    console.log(`数据库类型: ${databaseType}`);
    console.log(`前端端口: ${webPort}`);
    console.log(`后端端口: ${apiPort}`);
    console.log(`邮箱验证: ${enableEmailVerification ? '启用' : '禁用'}`);

    // 确认配置
    const confirmed = await confirmQuestion('\n确认以上配置并继续?');
    if (!confirmed) {
      colorLog('yellow', '初始化已取消');
      rl.close();
      return;
    }

    // 开始配置
    colorLog('\n⚙️ 开始配置项目...');

    // 更新package.json
    updatePackageJson('name', appName.toLowerCase().replace(/\s+/g, '-'));
    updatePackageJson('description', appDescription);
    if (author) updatePackageJson('author', author);

    // 创建.env.local文件
    const config = {
      appName,
      appDescription,
      webPort,
      apiPort,
      databaseUrl,
      jwtSecret,
    };
    createEnvFile(config);
    colorLog('green', '✓ 创建 .env.local 文件');

    // 创建必要目录
    createDirectories();

    // 安装依赖
    colorLog('\n📦 安装依赖包...');
    const { spawn } = await import('child_process');
    
    await new Promise<void>((resolve, reject) => {
      const pnpm = spawn('pnpm', ['install'], {
        stdio: 'inherit',
        cwd: projectRoot,
      });
      
      pnpm.on('close', (code) => {
        if (code === 0) {
          colorLog('green', '✓ 依赖安装完成');
          resolve();
        } else {
          colorLog('red', '✗ 依赖安装失败');
          reject(new Error('依赖安装失败'));
        }
      });
    });

    // 生成Prisma客户端
    colorLog('\n🗄️ 生成数据库客户端...');
    await new Promise<void>((resolve, reject) => {
      const prisma = spawn('pnpm', ['--filter', 'database', 'db:generate'], {
        stdio: 'inherit',
        cwd: projectRoot,
      });
      
      prisma.on('close', (code) => {
        if (code === 0) {
          colorLog('green', '✓ Prisma客户端生成完成');
          resolve();
        } else {
          colorLog('red', '✗ Prisma客户端生成失败');
          reject(new Error('Prisma客户端生成失败'));
        }
      });
    });

    // 运行数据库迁移
    colorLog('\n🔄 运行数据库迁移...');
    await new Promise<void>((resolve, reject) => {
      const migrate = spawn('pnpm', ['--filter', 'database', 'db:migrate'], {
        stdio: 'inherit',
        cwd: projectRoot,
      });
      
      migrate.on('close', (code) => {
        if (code === 0) {
          colorLog('green', '✓ 数据库迁移完成');
          resolve();
        } else {
          colorLog('red', '✗ 数据库迁移失败');
          reject(new Error('数据库迁移失败'));
        }
      });
    });

    // 运行种子数据
    colorLog('\n🌱 初始化种子数据...');
    await new Promise<void>((resolve, reject) => {
      const seed = spawn('pnpm', ['--filter', 'database', 'db:seed'], {
        stdio: 'inherit',
        cwd: projectRoot,
      });
      
      seed.on('close', (code) => {
        if (code === 0) {
          colorLog('green', '✓ 种子数据初始化完成');
          resolve();
        } else {
          colorLog('yellow', '⚠ 种子数据初始化失败，但不影响正常使用');
          resolve();
        }
      });
    });

    // 完成
    colorLog('\n🎉 项目初始化完成！');
    colorLog('green', '\n🚀 启动开发服务器:');
    console.log('  pnpm dev          # 同时启动前后端');
    console.log('  pnpm dev:web      # 仅启动前端');
    console.log('  pnpm dev:api      # 仅启动后端');
    console.log('  pnpm db:studio    # 打开数据库管理界面');
    
    colorLog('\n📚 其他命令:');
    console.log('  pnpm build        # 构建项目');
    console.log('  pnpm test         # 运行测试');
    console.log('  pnpm lint         # 代码检查');
    console.log('  pnpm format       # 代码格式化');

    colorLog('\n🌐 访问地址:');
    console.log(`  前端: http://localhost:${webPort}`);
    console.log(`  后端: http://localhost:${apiPort}`);
    console.log(`  API文档: http://localhost:${apiPort}/docs`);

    colorLog('\n📖 测试账号:');
    console.log('  邮箱: test@example.com');
    console.log('  密码: Password123');

  } catch (error) {
    colorLog('red', `\n❌ 初始化失败: ${error}`);
    process.exit(1);
  } finally {
    rl.close();
  }
}

// 运行初始化
bootstrap();